include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    avoid_unnecessary_containers: true
    prefer_single_quotes: false
    sort_pub_dependencies: true
